version: "3"
services:
  app:
    image: node:8.12.0
    environment:
    - DEBUG=True
    - DOCKER_GATEWAY_IP=172.100.0.1
    command: sh -c 'npm install && npm test'
    volumes:
    - .:/app
    working_dir: /app
    depends_on:
      - martkist
    networks:
      - martkist
  martkist:
    image: salikausar/martkist-docker
    ports:
    - 8336:8368
    networks:
      - martkist
networks:
  martkist:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.100.0.0/16
